version: "3"

services:
  namenode:
    image: packet23/hadoop-hdfs-namenode:latest
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test

  datanode:
    image: packet23/hadoop-hdfs-datanode:latest
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
   
  
  
  
volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver: